### ISSUE TITLE
Frequently Asked Questions

### ISSUE THREAD

**Issue by abraswell** [CoPeCOMET/CoPeCOMET.github.io#11]
Not essential right this second. But definitely something we should put up eventually.

**Comment by ebgoldstein** [comment]
FAQ is in on the about page RN... I can beak it out? preference @abraswell ?

**Comment by abraswell** [comment]
I think break it out. I think websites are more intuitive when all the main categories are in the structure of the site, rather than on a page labelled something else.

**Comment by ebgoldstein** [comment]
done
