### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by abraswell** [CoPeCOMET/CoPeCOMET.github.io#17]
Was just thinking about how easy this website is to find. When I search for Cope Comet on google, it comes up with the NSF award page, but not this website (at least on the first page). And COMET comes up with all of the things you expect comet to come up with on google. Wondering if we need to put "COPE COMET" in the home page title somehow or use google search engine tricks to make it so that when you search "Cope Comet" it come up....thoughts?

**Comment by ebgoldstein** [comment]
https://bookdown.org/yihui/blogdown/useful-resources.html

**Comment by ebgoldstein** [comment]
added a website description in html in the header, and made new slugs with the words CoPe and COMET
